[package]
name = "ray_jspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7.0"
jonk_utils =  { path = "../jonk_utils" }
